# Generated by Django 3.2.3 on 2021-05-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail адрес')),
                ('theme', models.CharField(max_length=200, verbose_name='Тема сообщения')),
                ('description', models.CharField(max_length=12555, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.DeleteModel(
            name='contactForm',
        ),
    ]
